name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
  
    - name: Restore
      run: dotnet restore ./Github_CICD_Azure_Deployment/Github_CICD_Azure_Deployment.csproj
  
    - name: Build
      run: dotnet build ./Github_CICD_Azure_Deployment/Github_CICD_Azure_Deployment.csproj
  
    - name: Publish
      run: dotnet publish ./Github_CICD_Azure_Deployment/Github_CICD_Azure_Deployment.csproj --configuration Release --no-build --output './publish'

    - name: Deployment
      uses: azure/webapps-deploy@v2
    - with:
        app-name: basic-todo-app
        publish-profile: ${{secrets.AZURE_DEPLOYMENT_PROFILE}}
        package: './publish'
        
